version: '3.8'

services:
  no-space-alert:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    image: no-space-alert:latest
    init: true
    volumes:
      - ./logs:/app/logs
      - ${DOCKER_MOUNT_PATH_0:-/dev/null}:${DOCKER_MOUNT_PATH_0:-/mnt/mount_0}:ro
      - ${DOCKER_MOUNT_PATH_1:-/dev/null}:${DOCKER_MOUNT_PATH_1:-/mnt/mount_1}:ro
      - ${DOCKER_MOUNT_PATH_2:-/dev/null}:${DOCKER_MOUNT_PATH_2:-/mnt/mount_2}:ro
    command: ["start"]
    logging:
      driver: "json-file"
      options:
        max-size: "30m"
        max-file: "2"

networks:
  default:
    driver: bridge
    ipam:
      config:
        # - subnet: 10.10.1.0/24
        - subnet: 172.15.0.0/16
